name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.2

        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          port: 65002
          username: ${{ secrets.HOSTINGER_USER }}
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          script: |
            cd /home/u298762295/domains/sr-magallanes.com/public_html/mikasa
            git pull origin main